int     trap_GetApiVersion(  );
qboolean trap_GetEntityToken( char *token, int size );
void    trap_DPrintf( const char *fmt );
void    trap_BPrint( int level, const char *fmt );
void    trap_SPrint( int edn, int level, const char *fmt );
void    trap_CenterPrint( int edn, const char *fmt );
void    trap_Error( const char *fmt );
int     trap_spawn(  );
void    trap_remove( int edn );
void    trap_precache_sound( char *name );
void    trap_precache_model( char *name );
void    trap_setorigin( int edn, float origin_x, float origin_y, float origin_z );
void    trap_setsize( int edn, float min_x, float min_y, float min_z, float max_x,
		      float max_y, float max_z );
void    trap_setmodel( int edn, char *model );
void    trap_ambientsound( float pos_x, float pos_y, float pos_z, char *samp, float vol,
			   float atten );
void    trap_sound( int edn, int channel, char *samp, int vol, float att );
int     trap_checkclient(  );
void    trap_traceline( float v1_x, float v1_y, float v1_z, float v2_x, float v2_y,
			float v2_z, int nomonst, int edn );
void    trap_stuffcmd( int edn, const char *fmt );
void    trap_localcmd( const char *fmt );
float   trap_cvar( const char *var );
void    trap_cvar_set( const char *var, const char *val );
int     trap_droptofloor( int edn );
int     trap_walkmove( int edn, float yaw, float dist );
void    trap_lightstyle( int style, char *val );
int     trap_checkbottom( int edn );
int     trap_pointcontents( float origin_x, float origin_y, float origin_z );
int     trap_nextent( int n );
void    trap_makestatic( int edn );
void    trap_setspawnparam( int edn );
void    trap_changelevel( char *name );
int     trap_multicast( float origin_x, float origin_y, float origin_z, int to );
void    trap_logfrag( int killer, int killee );
void    trap_infokey( int edn, char *key, char *valbuff, int sizebuff );
void    trap_WriteByte( int to, int data );
void    trap_WriteChar( int to, int data );
void    trap_WriteShort( int to, int data );
void    trap_WriteLong( int to, int data );
void    trap_WriteAngle( int to, float data );
void    trap_WriteCoord( int to, float data );
void    trap_WriteString( int to, char *data );
void    trap_WriteEntity( int to, int edn );
void    trap_FlushSignon(  );
void    trap_disableupdates( int edn, float time );
int     trap_CmdArgc(  );
void    trap_CmdArgv( int arg, char *valbuff, int sizebuff );
